# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os, sys
sys.path.insert(0, os.path.abspath('./scripts/'))


# -- Project information -----------------------------------------------------

project = u'VMI Bootcamp II'
copyright = u'2018, Andrew Brooks, Matt Scholz, Seth Bordenstein'
author = u'Andrew Brooks, Matt Scholz, Seth Bordenstein'

# The short X.Y version
version = u''
# The full version, including alpha/beta/rc tags
release = u'1.0'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [u'_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'classic'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# CSS COLORS:
# Black - #000000
# White - #ffffff
# Dark Dark Grey - #404040
# Dark Grey - #595959
# Grey - #737373
# Light Grey - #a6a6a6
# Light Light Grey - #e6e6e6
# Gold - #f4d442
# Blue - #0000ff
# Light Blue - #4dc3ff
# Light Green - #99ff33


html_theme_options = {  

   ### SIDE BAR ###
   "nosidebar": "false", # (true or false): Don’t include the sidebar. Defaults to False.
   "rightsidebar": "false", # (true or false): Put the sidebar on the right side. Defaults to False.
   "sidebarwidth": "20%", # (int or str): Width of the sidebar in pixels. This can be an int, which is interpreted as pixels or a valid CSS dimension string such as ‘70em’ or ‘50%’. Defaults to 230 pixels.
   "sidebarbgcolor": "#404040", # Background color for the sidebar.
   "sidebartextcolor": "gold", # Text color for the sidebar.
   "sidebarlinkcolor": "#ffffcc", # Link color for the sidebar.  
#   "collapsiblesidebar": "false", # (true or false): Add an experimental JavaScript snippet that makes the sidebar collapsible via a button on its side. Defaults to False.
#   "sidebarbtncolor": "black", # Background color for the sidebar collapse button (used when collapsiblesidebar is True).

   
   ### BODY ###
   "body_min_width": "0", # (int or str): Minimal width of the document body. This can be an int, which is interpreted as pixels or a valid CSS dimension string such as ‘70em’ or ‘50%’. Use 0 if you don’t want a width limit. Defaults may depend on the theme (often 450px).
   "body_max_width": "100%", # (int or str): Maximal width of the document body. This can be an int, which is interpreted as pixels or a valid CSS dimension string such as ‘70em’ or ‘50%’. Use ‘none’ if you don’t want a width limit. Defaults may depend on the theme (often 800px).
   "bodyfont": "arial", # (CSS font-family): Font for normal text.
   "bgcolor": "white", # Body background color.
   "textcolor": "black", # Body text color.
#   "linkcolor": "blue", # Body link color.
#   "visitedlinkcolor": "light blue", # Body color for visited links.

   ### RELATION BAR ### Bar across the top with links
   "relbarbgcolor": "#595959", # Background color for the relation bar.
   "relbartextcolor": "gold", # Text color for the relation bar.
   "relbarlinkcolor": "gold", # Link color for the relation bar.
   
   ### FOOTER ###
   "footerbgcolor": "#404040", # Background color for the footer line.
   "footertextcolor": "gold", # Text color for the footer line.

   ### HEADER ###
   "headbgcolor": "#e6e6e6", # Background color for headings.
   "headtextcolor": "black", # Text color for headings.
#   "headlinkcolor": "blue", # Link color for headings.
   "headfont": "arial", # (CSS font-family): Font for headings.
   
   ### CODE ###
   "codebgcolor": "black", # Background color for code blocks.
   "codetextcolor": "#ffffcc", # Default text color for code blocks, if not set differently by the highlighting style.
   
   
   
   }


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'VMIBootcampIIdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'VMIBootcampII.tex', u'VMI Bootcamp II Documentation',
     u'Andrew Brooks, Matt Scholz, Seth Bordenstein', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'vmibootcampii', u'VMI Bootcamp II Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'VMIBootcampII', u'VMI Bootcamp II Documentation',
     author, 'VMIBootcampII', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------